Configuration:
  name: Default
  Properties:
    Property:
      name: log-path
      value: ../logs
  Appenders:
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "[%-5level] %d"